---
- name: Add to fstab
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/fstab
    regexp: '{{swap_file}}'
    line: '{{swap_file}} none swap sw 0 0'
    state: present

- name: Turn swap on
  become: true
  become_user: root
  command: swapon -a