---
- name: Add systemd drop-in for swap
  become: true
  become_user: root
  register: swap_systemd_dropin
  template:
    src: swapfile.j2
    dest: /etc/systemd/system/{{swap_file}}.swap

- name: init-system reload
  when: swap_systemd_dropin|changed
  become: yes
  become_user: root
  command: systemctl daemon-reload
