---
- name: Add systemd drop-in for swap
  become: true
  become_user: root
  register: swap_systemd_dropin
  template:
    src: swapfile.j2
    dest: /etc/systemd/system/{{swap_file_name}}.swap

- name: start systemctl unit for swap file
  become: yes
  become_user: root
  when: swap_systemd_dropin|changed
  systemd:
    name: '{{swap_file_name}}.swap'
    daemon_reload: yes
    state: restarted
    enabled: True